# Generated by Django 4.1.5 on 2023-01-21 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_table', models.TextField(default='', verbose_name='HTML таблица')),
            ],
            options={
                'verbose_name': 'Востребованность (таблицы)',
                'verbose_name_plural': 'Востребованность (таблицы)',
            },
        ),
        migrations.CreateModel(
            name='Geo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_table', models.TextField(default='', verbose_name='HTML таблица')),
            ],
            options={
                'verbose_name': 'География (таблицы)',
                'verbose_name_plural': 'География (таблицы)',
            },
        ),
        migrations.CreateModel(
            name='Homeblocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Заголовок', help_text='Введите значение', max_length=50, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Блок информации на главной',
                'verbose_name_plural': 'Блоки с информацией на главной',
            },
        ),
        migrations.CreateModel(
            name='Topskills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_table', models.TextField(default='', verbose_name='HTML таблица')),
            ],
            options={
                'verbose_name': 'Навыки (таблицы)',
                'verbose_name_plural': 'Навыки (таблицы)',
            },
        ),
        migrations.CreateModel(
            name='ChartGeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название таблицы')),
                ('image', models.ImageField(default='', upload_to='charts/', verbose_name='График')),
                ('geo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.geo', verbose_name='График')),
            ],
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название таблицы')),
                ('image', models.ImageField(default='', upload_to='charts/', verbose_name='График')),
                ('demand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.demand', verbose_name='График')),
            ],
        ),
    ]
