# Generated by Django 4.1.5 on 2023-01-22 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название таблицы')),
                ('image', models.ImageField(default='', upload_to='chart2/', verbose_name='График')),
                ('geo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.geo', verbose_name='График')),
            ],
        ),
        migrations.AlterField(
            model_name='chart',
            name='image',
            field=models.ImageField(default='', upload_to='chart/', verbose_name='График'),
        ),
        migrations.DeleteModel(
            name='ChartGeo',
        ),
    ]
