# Generated by Django 4.1.5 on 2023-01-22 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_chart3'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='Название таблицы'),
        ),
        migrations.AddField(
            model_name='geo',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='Название таблицы'),
        ),
        migrations.AddField(
            model_name='topskills',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='Название таблицы'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='image',
            field=models.ImageField(default='', upload_to='charts/', verbose_name='График'),
        ),
        migrations.AlterField(
            model_name='chart2',
            name='image',
            field=models.ImageField(default='', upload_to='charts/', verbose_name='График'),
        ),
        migrations.AlterField(
            model_name='chart3',
            name='image',
            field=models.ImageField(default='', upload_to='charts/', verbose_name='График'),
        ),
    ]
